[package]
name = "sequencer"
version = "0.1.0"
authors = ["Richard South <southy98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
pretty_env_logger = "0.4.0"
regex = "1.4.6"
itertools = "0.10.0"
raqote = { version="0.8.0", features = [ "pathfinder_geometry" ] }
# "text", "font-kit",
#font-kit = "0.7.0"
pathfinder_geometry = "0.5.1"
euclid = "0.22.3"
#rusttype = "0.9.2"
#font-kit = "0.10.0"
#itertools = "0.10.0"
#smallset = "0.1.1"
#rayon = "1.5.0"
#linked_hash_set = "0.1.4"
smallvec = "1.6.1"
lazy_static = "1.4.0"

fontdue = "0.5.0"
#gfx_glyph = "0.17.0"

[dev-dependencies]
criterion = { version = "0.3", features = [ "html_reports" ] }

[[bench]]
name = "benchmark_parsing"
harness = false

#[[bench]]
#name = "benchmark_rendering"
#harness = false

#[[bench]]
#name = "text_benchmarks"
#harness = false

